
package com.rawat;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DBMethods", targetNamespace = "http://rawat.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DBMethods {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.rawat.EmpTable>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchTableRecords", targetNamespace = "http://rawat.com", className = "com.rawat.FetchTableRecords")
    @ResponseWrapper(localName = "fetchTableRecordsResponse", targetNamespace = "http://rawat.com", className = "com.rawat.FetchTableRecordsResponse")
    @Action(input = "http://rawat.com/DBMethods/fetchTableRecordsRequest", output = "http://rawat.com/DBMethods/fetchTableRecordsResponse")
    public List<EmpTable> fetchTableRecords(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "avgFinder", targetNamespace = "http://rawat.com", className = "com.rawat.AvgFinder")
    @ResponseWrapper(localName = "avgFinderResponse", targetNamespace = "http://rawat.com", className = "com.rawat.AvgFinderResponse")
    @Action(input = "http://rawat.com/DBMethods/avgFinderRequest", output = "http://rawat.com/DBMethods/avgFinderResponse")
    public float avgFinder();

}
