
package com.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Message", targetNamespace = "http://test.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Message {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMsg", targetNamespace = "http://test.com/", className = "com.test.GetMsg")
    @ResponseWrapper(localName = "getMsgResponse", targetNamespace = "http://test.com/", className = "com.test.GetMsgResponse")
    @Action(input = "http://test.com/Message/getMsgRequest", output = "http://test.com/Message/getMsgResponse")
    public String getMsg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
